# Form implementation generated from reading ui file 'newview.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 710)
        MainWindow.setMinimumSize(QtCore.QSize(440, 710))
        MainWindow.setMaximumSize(QtCore.QSize(220, 355))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.entry1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.entry1.setGeometry(QtCore.QRect(60, 100, 113, 21))
        self.entry1.setObjectName("entry1")
        self.entry2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.entry2.setGeometry(QtCore.QRect(280, 100, 113, 21))
        self.entry2.setObjectName("entry2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 321, 81))
        self.label.setObjectName("label")
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(110, 400, 241, 131))
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.SUBMIT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SUBMIT.setGeometry(QtCore.QRect(170, 340, 113, 32))
        self.SUBMIT.setObjectName("SUBMIT")
        self.button_sin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_sin.setGeometry(QtCore.QRect(40, 250, 100, 32))
        self.button_sin.setObjectName("button_sin")
        self.button_cos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cos.setGeometry(QtCore.QRect(160, 250, 100, 32))
        self.button_cos.setObjectName("button_cos")
        self.button_tan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_tan.setGeometry(QtCore.QRect(290, 250, 100, 32))
        self.button_tan.setObjectName("button_tan")
        self.button_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(20, 150, 100, 32))
        self.button_plus.setObjectName("button_plus")
        self.button_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(120, 150, 100, 32))
        self.button_minus.setObjectName("button_minus")
        self.button_times = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_times.setGeometry(QtCore.QRect(220, 150, 100, 32))
        self.button_times.setObjectName("button_times")
        self.button_divide = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_divide.setGeometry(QtCore.QRect(320, 150, 100, 32))
        self.button_divide.setObjectName("button_divide")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "Enter two numbers! Note: When using trig functions, \n"
"only the first number is considered"))
        self.SUBMIT.setText(_translate("MainWindow", "CLEAR"))
        self.button_sin.setText(_translate("MainWindow", "sin"))
        self.button_cos.setText(_translate("MainWindow", "cos"))
        self.button_tan.setText(_translate("MainWindow", "tan"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_times.setText(_translate("MainWindow", "x"))
        self.button_divide.setText(_translate("MainWindow", "÷"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
